<!-- # Parts -->

<!-- You can add parts to organize one or more book chapters together. Parts can be inserted at the top of an .Rmd file, before the first-level chapter heading in that same file.  -->

<!-- Add a numbered part: `# (PART) Act one {-}` (followed by `# A chapter`) -->

<!-- Add an unnumbered part: `# (PART\*) Act one {-}` (followed by `# A chapter`) -->

<!-- Add an appendix as a special kind of un-numbered part: `# (APPENDIX) Other stuff {-}` (followed by `# A chapter`). Chapters in an appendix are prepended with letters instead of numbers. -->



# Matériel et méthodes
Ce rapport couvre une période de huit ans, de 1999 à 2006,
depuis que le système sur la mortalité hospitalière mis en
place par le SEMEP existe. Tous les décès survenus au CHU
étaient activement recensés par les techniciens du SEMEP au
niveau des différents services, avec l’aide des bureaux des
entrées des trois unités du CHU.
La Classification internationale des maladies (CIM-9) et
ses règles de classement ont été utilisées pour coder la nature
de la maladie causale, tandis que les opérations de saisie, de
contrôle et d’analyse ont été effectuées par l’utilisation du
logiciel Épi-Info™ dans sa sixième version.
Le système sur la mortalité hospitalière mis en place par le
SEMEP permet de déterminer la mortalité proportionnelle
(MP) occasionnée par la mortalité néonatale (nombre de
décès néonatals sur l’ensemble des décès). Le dénominateur
utilisé pour estimer le taux de mortalité néonatale au CHU
provient des données appartenant au registre d’admission du
service de pédiatrie, au registre des naissances vivantes du
service de gynécologie-obstétrique. Celui-ci, avec le service
de pédiatrie, appartient à la même unité de lieu constituée par
le complexe mère-enfant du CHU. Il a par ailleurs été tenu
compte des nouveau-nés transférés des maternités périphériques
ou d’autres hôpitaux.
L’analyse des séries chronologiques a essentiellement fait
appel au coefficient de corrélation (r) ainsi qu’au coefficient
de corrélation des rangs de Spearman (r0). Le coefficient de
corrélation r était déterminé pour apprécier l’évolution
temporelle du nombre mensuel de décès néonatals, tandis
que le coefficient de corrélation r0 était déterminé pour
apprécier la tendance dessinée par le taux annuel de la
mortalité néonatale et de la proportion annuelle des nouveaunés
transférés des maternités périphériques au cours de la
période d’étude. L’analyse des séries chronologiques a
également fait appel à l’analyse de plans factoriels à une
répétition pour déceler un éventuel effet des variables du plan
[6]. Sauf indication contraire, les moyennes étaient accompagnées
des écarts-types des valeurs des différentes séries.
La prématurité a été définie comme l’état d’un nouveau-né
déclaré né avant la 37e semaine d’aménorrhée d’une
gestation, tandis qu’un cas de décès néonatal précoce a
concerné un nouveau-né déclaré né vivant après une
grossesse de 25 semaines au minimum.