# Résultats
Au total, 8 541 décès ont été enregistrés au CHU de Blida
de 1999 à 2006, dont 2 167 décès néonatals, soit une MP de
25,4 %. Autrement dit, un décès sur quatre survenant au
CHU de Blida concernait un nouveau-né âgé de moins
de 29 jours. La MP occasionnée par la mortalité néonatale

occupait la première position et devançait celle des maladies
de l’appareil circulatoire (21 %) et celle des traumatismes et
empoisonnements (19,8 %) qui occupaient respectivement
les deuxième et troisième position.
La mortalité néonatale précoce (0-6 jours) avec 1 808
décès a représenté 83,4 % de l’ensemble de la mortalité
néonatale, tandis que la mortalité néonatale tardive
(7-28 jours), avec 359 décès, a représenté 16,6 % de
l’ensemble de la mortalité néonatale. Il existait une relation
entre l’année (comme variable servant de base aux
comparaisons) et le type de mortalité : la fréquence relative
de la mortalité néonatale précoce en 1999 (76,8 %) était plus
basse (p < 0,02). Mais dans l’ensemble, d’une année à une
autre, la mortalité néonatale précoce représentait plus des
quatre cinquièmes de la mortalité néonatale globale.
La mortalité néonatale proportionnelle dans ses deux
composantes est pratiquement restée stationnaire pendant la
période d’étude, malgré une hausse en 2003 qui a affecté la
mortalité néonatale précoce (Tableau 1).
Parmi les décès néonatals précoces, 24,0 % sont intervenus
avant le premier jour de vie, tandis que près des deux
tiers (63,0 %) des décès sont intervenus dans les trois
premiers jours de vie. Pour les décès néonatals tardifs,
37,6 % sont survenus entre sept et dix jours de vie.
L’évolution annuelle de la répartition des décès néonatals
précoces et tardifs selon l’âge en jours révolus du décès
ne mettait pas en évidence de différence significative
(Tableau 2).


L’évolution mensuelle (8 × 12 = 96 mois) du nombre de
décès néonatals précoces a dessiné une tendance significativement
à la hausse au cours de la période d’étude (r = 0,21,
p < 0,05), tandis que la mortalité néonatale tardive a dessiné
une tendance à la baisse, mais de façon non significative
(r = –0,18 NS). La résultante en est une tendance à la hausse
de la mortalité néonatale globale au cours de la période
d’étude, mais de façon non significative (r = 0,13 NS).
Pour la mortalité néonatale précoce, l’analyse du plan
factoriel relatif à l’année et au mois de l’année n’a pas mis en
évidence un effet saisonnier (F = 1,34 NS), tandis qu’un
excès de décès était notamment enregistré pour l’année 2003
(F = 4,25 NS, p < 0,001). L’analyse du plan factoriel relatif
au jour de la semaine et à l’heure du jour n’a mis en évidence
ni un effet d’heure (F = 1,54 NS) ni un effet de jour de
semaine (F = 0,69 NS).
D’une année à une autre, la prématurité a représenté, en
règle générale, plus de 40 % des causes de décès de la
mortalité néonatale précoce, suivie par le syndrome de
détresse respiratoire et les infections néonatales, respectivement
17 et 14,4 %.
Les infections ont représenté, pour la mortalité néonatale
tardive, la cause la plus fréquente avec 43,8 % des causes de
décès en 1999 : cette proportion a ensuite régulièrement
baissé au cours du temps pour représenter, en 2006,
20,6 % des causes de décès (Tableau 3).
Le rapport de masculinité était de 1,5 pour la mortalité
néonatale globale. Le rapport de masculinité restait


pratiquement le même, aussi bien pour la phase précoce que
pour la phase tardive, respectivement de 1,4 et 1,5.
Cependant, il n’existait pas de relation entre le type
de mortalité et le sexe : la mortalité néonatale précoce
a représenté respectivement 83 et 84 % de la mortalité
néonatale chez les nouveau-nés de sexe masculin et
ceux de sexe féminin. Les causes de décès chez les deux
sexes ne semblaient pas non plus différer sensiblement
(Tableau 4).


La durée de séjour moyenne des enfants décédés en
période néonatale précoce pendant la période d’étude était
de 1,4 ± 0,0 jour (moyenne ± erreur type), tandis que la
médiane était de 1 jour. D’une année à une autre, cette
moyenne n’a pas varié de façon significative. La durée de
séjour moyenne des enfants décédés en période néonatale
tardive était de 8,5 ± 0,3 jours (médiane = 8 jours) ; la
durée de séjour moyenne en 1999 était relativement basse
(Tableau 5).


Les taux estimés de mortalité néonatale précoce et tardive,
lorsque ces taux admettent comme dénominateur le nombre
de nouveau-nés admis en néonatalogie pour exprimer la
mortalité de service, ont dessiné une tendance significativement
à la baisse expliquant par là même la tendance à la
baisse du taux de mortalité globale. Par contre, aucune
tendance temporelle significative n’était mise en évidence
lorsque les taux sont exprimés en fonction du nombre de
naissances vivantes (Tableau 6).
Le taux de mortalité néonatale précoce pendant la période
d’étude (1999-2006), en prenant en dénominateur le nombre
de nouveau-nés admis en néonatalogie, était de 15,6 %,
tandis que le taux de mortalité tardive correspondant était de
3,1 %, soit un taux de mortalité néonatale globale de 18,7 %.
On pouvait donc raisonnablement estimer que chaque
nourrisson admis en néonatalogie avait presque une
probabilité de 1/6 de décéder avant le septième jour de vie.

Le taux de mortalité néonatale précoce, en prenant comme
dénominateur le nombre de naissances vivantes enregistrées
dans l’établissement, était, pendant la période d’étude, de
22,9 pour 1 000, tandis que le taux de mortalité néonatale
tardive était de 4,5 pour 1 000, soit un taux de mortalité
néonatale globale de 27,4 pour 1 000.
Les nouveau-nés transférés des maternités périphériques
ont représenté 20,4 % des nouveau-nés admis en néonatalogie
(2 366-11 612) et 2,9 % des naissances vivantes
(2 366-81 345) au CHU de Blida. Le nombre des décédés
parmi les transférés s’est élevé à 410, soit une proportion de
17,3 % (410-2 366).
Le taux de mortalité néonatale globale au CHU de Blida,
pendant toute la période d’étude, pouvait alors, en soustrayant
les décès parmi les transférés, être plus justement estimé à
22,3 pour 1 000 naissances vivantes (1 757-78 879), soit une
diminution de 18,9 % par rapport au taux qui ne tiendrait

pas compte des décès survenus parmi les nouveau-nés
transférés.
Pendant toute la période d’étude, le taux de mortalité
néonatale précoce, en déduisant les décès survenus parmi les
nouveau-nés transférés (294 décès), pouvait être estimé à
19,2 pour 1 000 naissances vivantes, soit une diminution
de 16,2 % par rapport au taux qui ne tiendrait pas compte de
ces décès.
De même, le taux de mortalité néonatale tardive, en
retranchant les décès parmi les transférés (116 décès),
pouvait être estimé pendant toute la période d’étude à 3,1
pour 1 000 naissances vivantes, soit une diminution de
31,1 % par rapport au taux qui ne tiendrait pas compte de ces
décès.