<!-- # Sharing your book -->

<!-- ## Publishing -->

<!-- HTML books can be published online, see: https://bookdown.org/yihui/bookdown/publishing.html -->

<!-- ## 404 pages -->

<!-- By default, users will be directed to a 404 page if they try to access a webpage that cannot be found. If you'd like to customize your 404 page instead of using the default, you may add either a `_404.Rmd` or `_404.md` file to your project root and use code and/or Markdown syntax. -->

<!-- ## Metadata for sharing -->

<!-- Bookdown HTML books will provide HTML metadata for social sharing on platforms like Twitter, Facebook, and LinkedIn, using information you provide in the `index.Rmd` YAML. To setup, set the `url` for your book and the path to your `cover-image` file. Your book's `title` and `description` are also used. -->

# Conclusion
L’Algérie a pris conscience du lourd fardeau représenté par la
mortalité néonatale en mettant en place un Programme
triennal national sur la périnatalité. La surveillance de la
grossesse et du travail, d’une part, et la prise en charge
immédiate du nouveau-né par une équipe obstétricopédiatrique,
d’autre part, sont les deux piliers de ce programme,
dont des objectifs quantifiés concernent, par exemple, une
réduction de 25 % de la mortalité néonatale précoce et une
réduction de 30 % de la mortalité des nouveau-nés de faible
poids de naissance d’ici 2009 [18].
Les données du CHU de Blida sur la mortalité néonatale,
décrivant une période fort homogène, devraient contribuer
à mesurer le degré d’atteinte d’objectifs fixés de ce
programme, d’autant plus que le risque de mortalité
néonatale déterminé pour le CHU rejoint celui enregistré à
l’échelle nationale.

This `gitbook` uses the same social sharing data across all chapters in your book- all links shared will look the same.

Specify your book's source repository on GitHub using the `edit` key under the configuration options in the `_output.yml` file, which allows users to suggest an edit by linking to a chapter's source file. 

Read more about the features of this output format here:

https://pkgs.rstudio.com/bookdown/reference/gitbook.html

Or use:

```{r eval=FALSE}
?bookdown::gitbook
```


